P5 E-Learning/force-app/main/default/objects/Answer_For_Progress__c/Answer_For_Progress__c.object-meta.xml
<CustomObject>
    <label>Answer For Progress</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Answer For Progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers For Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Answer_For_Progress__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Answers For Progresses</relationshipLabel>
    <relationshipName>Answers_For_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Answer_For_Progress__c/fields/Progress_Unit_Per_Response__c.field-meta.xml
<CustomField>
    <fullName>Progress_Unit_Per_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Progress Unit Per Response</label>
    <referenceTo>Progress_Unit_Per_Response__c</referenceTo>
    <relationshipLabel>Answers For Progresses</relationshipLabel>
    <relationshipName>Answers_For_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Option__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True means Yes</description>
    <label>Is Correct</label>
    <type>Checkbox</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Progress_Unit_Per_Response__c/Progress_Unit_Per_Response__c.object-meta.xml
<CustomObject>
    <label>Progress Unit Per Response</label>
    <nameField>
        <displayFormat>PU-{0}</displayFormat>
        <label>Progress Unit Per Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progresses Unit Per Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Progress_Unit_Per_Response__c/fields/Tries__c.field-meta.xml
<CustomField>
    <fullName>Tries__c</fullName>
    <label>Tries</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Progress_Unit_Per_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Progresses Unit Per Responses</relationshipLabel>
    <relationshipName>Progresses_Unit_Per_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Progress_Unit_Per_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <formula>CASESAFEID( Progress_Module_Per_Unit__r.User__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User</label>
    <type>Text</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/classes/unitResponseTrigger.cls
public with sharing class unitResponseTrigger {
            
    public static void onBeforeUpdate(List<Progress_Unit_Per_Response__c> progressunitResponseList, Map<Id, Progress_Unit_Per_Response__c> oldUnitRespMap){

        List<Progress_Unit_Per_Response__c> answeredUnitRespList = new  List<Progress_Unit_Per_Response__c>();
        for(Progress_Unit_Per_Response__c unitResp : progressunitResponseList){
            if(unitResp.Status__c == 'Answered' && oldUnitRespMap.get(unitResp.Id).Status__c == 'Draft'){
            answeredUnitRespList.add(unitResp);
            }   
        }
        evaluateAnswers(answeredUnitRespList);
    }

public static void onAfterUpdate(List<Progress_Unit_Per_Response__c> progressunitResponseList, Map<Id,  Progress_Unit_Per_Response__c> oldUnitRespMap){

    List<Progress_Unit_Per_Response__c> successAnsweredUnitRespList = new  List<Progress_Unit_Per_Response__c>();
    for(Progress_Unit_Per_Response__c unitResp : progressunitResponseList){
        if(unitResp.Status__c == 'Success' && oldUnitRespMap.get(unitResp.Id).Status__c == 'Answered'){
            successAnsweredUnitRespList.add(unitResp);
        }
    }  
    
    updateUserScore(successAnsweredUnitRespList);
}


private static void updateUserScore(List<Progress_Unit_Per_Response__c> progressUnitResponseList){

    //recoleto todos los userIs de la lista que viene por parametro.
    Set<Id> userIds = new Set<Id>();
    for(Progress_Unit_Per_Response__c unitResp :progressUnitResponseList){
        userIds.add(unitResp.User__c);
    }
    //busco los usuarios relacionesdos a las unit response

    Map<Id, User> unitRespoByUserId = new Map<Id,User>([SELECT Score__c FROM User WHERE Id IN:userIds]);

    //Actualizo el score en base a la unit response.
    for(Progress_Unit_Per_Response__c unitResp:  progressUnitResponseList){
        User user = unitRespoByUserId.get(unitResp.User__c);

        user.Score__c += unitResp.Score__c;
    }

    update unitRespoByUserId.values();
}

private static void evaluateAnswers(List<Progress_Unit_Per_Response__c> progressUnitResponseList){

    Map<Id, Progress_Unit_Per_Response__c> unitPerRespQueryMap = new Map<Id, Progress_Unit_Per_Response__c>([SELECT Id, Unit__r.Score__c, (SELECT Id, Option__r.Is_Correct__c FROM Answers_For_Progresses__r) FROM Progress_Unit_Per_Response__c WHERE Id IN:progressUnitResponseList  ]);

    for(Progress_Unit_Per_Response__c unitResp : progressUnitResponseList){ 
        
        Progress_Unit_Per_Response__c unitRespFromDb =  unitPerRespQueryMap.get(unitResp.Id);
        
        unitResp.Status__c = 'Success';

        for(Answer_For_Progress__c answerForProgress : unitRespFromDb.Answers_For_Progresses__r){
   
             if(!answerForProgress.Option__r.Is_Correct__c){
                unitResp.Status__c = 'Fail';
                break;
            }
        }

        if(unitResp.Status__c == 'Success'){
            if(unitResp.Tries__c == 1){
                unitResp.Score__c = unitRespFromDb.Unit__r.Score__c;  

            }else if(unitResp.Tries__c == 2){
                unitResp.Score__c = unitRespFromDb.Unit__r.Score__c / 2; 

            }else{
                unitResp.Score__c = unitRespFromDb.Unit__r.Score__c / 4;
            }
        }
    }      
}   



}